###############################################
#CS570 - SUMMER 2013
#Name: Linh Ngoc Nguyen
#Username: masc0939
#Project: CS570 CSNNNN Assignment 3
#Partner: Thon Saetern
#Username: masc0954
#File: Makefile
###############################################
a3: a3.cpp time_countdown.cpp
	g++ -o a3 a3.cpp time_countdown.cpp
