scl: a2.c sic.c sicXE.c read_file.c convert_file.c create_file_list.c create_obj_code.c create_obj_codeXE.c
	g++ -o scl a2.c sic.c sicXE.c read_file.c convert_file.c create_file_list.c  create_obj_code.c create_obj_codeXE.c
