###############################################
#CS570 - SUMMER 2013
#Name: Linh Ngoc Nguyen
#Username: masc0939
#Project: CS570 CSNNNN Assignment 2
#Partner: Thon Saetern
#Username: masc0954
#File: Makefile
###############################################
a2: a2.cpp pageAl.cpp
	g++ -o a2 a2.cpp pageAl.cpp
